In [1]:
# !pip install -U -q PyDrive
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

In [2]:
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

In [3]:
# pip install --upgrade tensorflow

In [4]:
# #https://drive.google.com/file/d/1XclUY4dJp7PnwwWUCILV5AzSvzK-3RYT/view?usp=sharing
# id='1XclUY4dJp7PnwwWUCILV5AzSvzK-3RYT'

import pandas as pd

# downloaded = drive.CreateFile({'id':id}) 
# downloaded.GetContentFile('Merged_All_pc_df.csv')  
df = pd.read_csv('Merged_All_pc_df.csv')

In [5]:
df

Unnamed: 0  Michael Lehmann  Tim Johnson  \
0        *batteries not included                0            0   
1     10 Things I Hate About You                0            0   
2                    10,000 B.C.                0            0   
3                 101 Dalmatians                0            0   
4                 101 Dalmatians                0            0   
...                          ...              ...          ...   
4344                 Zoolander 2                0            0   
4345                    Zootopia                0            0   
4346                        Zulu                0            0   
4347  xXx: Return of Xander Cage                0            0   
4348     xXx: State of the Union                0            0   

      Christopher Miller  Louis Leterrier  Raja Gosnell  Steve Oedekerk  \
0                      0                0             0               0   
1                      0                0             0               0   
2                      0                0             0               0   
3                      0                0             0               0   
4                      0                0             0               0   
...                  ...              ...           ...             ...   
4344                   0                0             0               0   
4345                   0                0             0               0   
4346                   0                0             0               0   
4347                   0                0             0               0   
4348                   0                0             0               0   

      Sidney Lumet  Richard Donner  Joel Coen  ...  Western  Drama  Classics  \
0                0               0          0  ...        0      0         0   
1                0               0          0  ...        0      0         0   
2                0               0          0  ...        0      1         1   
3                0               0          0  ...        0      0         1   
4                0               0          0  ...        0      0         1   
...            ...             ...        ...  ...      ...    ...       ...   
4344             0               0          0  ...        0      0         0   
4345             0               0          0  ...        0      0         0   
4346             0               0          0  ...        0      1         1   
4347             0               0          0  ...        0      1         0   
4348             0               0          0  ...        0      0         0   

      Special Interest  Romance  Television  content_rating  runtime  \
0                    0        0           0               G    106.0   
1                    0        0           0           PG-13     97.0   
2                    0        0           0           PG-13    109.0   
3                    0        0           0               G     79.0   
4                    0        0           0               G    103.0   
...                ...      ...         ...             ...      ...   
4344                 0        0           0           PG-13    102.0   
4345                 0        0           0              PG    108.0   
4346                 0        0           0              PG    135.0   
4347                 0        0           0           PG-13    102.0   
4348                 0        0           0               R    100.0   

      production_company  audience_rating  
0     Universal Pictures               64  
1            Buena Vista               69  
2           Warner Bros.               37  
3            Buena Vista               76  
4            Buena Vista               40  
...                  ...              ...  
4344           Paramount               20  
4345              Disney               92  
4346           Paramount               91  
4347           Paramount               37  
4348              

In [6]:
from numpy.random import seed
import numpy as np
import tensorflow
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder

In [7]:
runtime = df["runtime"]
runtime

0       106.0
1        97.0
2       109.0
3        79.0
4       103.0
        ...  
4344    102.0
4345    108.0
4346    135.0
4347    102.0
4348    100.0
Name: runtime, Length: 4349, dtype: float64

In [8]:
runtime.min()

8.0

In [9]:
runtime.max()

254.0

In [10]:
runtime = pd.DataFrame(runtime)

In [11]:
df.loc[df["runtime"] <= 90, "runtime"] = 1
df.loc[df["runtime"].between(90,120), "runtime"] = 2
df.loc[df["runtime"] >= 120, "runtime"] = 3

In [12]:
df

Unnamed: 0  Michael Lehmann  Tim Johnson  \
0        *batteries not included                0            0   
1     10 Things I Hate About You                0            0   
2                    10,000 B.C.                0            0   
3                 101 Dalmatians                0            0   
4                 101 Dalmatians                0            0   
...                          ...              ...          ...   
4344                 Zoolander 2                0            0   
4345                    Zootopia                0            0   
4346                        Zulu                0            0   
4347  xXx: Return of Xander Cage                0            0   
4348     xXx: State of the Union                0            0   

      Christopher Miller  Louis Leterrier  Raja Gosnell  Steve Oedekerk  \
0                      0                0             0               0   
1                      0                0             0               0   
2                      0                0             0               0   
3                      0                0             0               0   
4                      0                0             0               0   
...                  ...              ...           ...             ...   
4344                   0                0             0               0   
4345                   0                0             0               0   
4346                   0                0             0               0   
4347                   0                0             0               0   
4348                   0                0             0               0   

      Sidney Lumet  Richard Donner  Joel Coen  ...  Western  Drama  Classics  \
0                0               0          0  ...        0      0         0   
1                0               0          0  ...        0      0         0   
2                0               0          0  ...        0      1         1   
3                0               0          0  ...        0      0         1   
4                0               0          0  ...        0      0         1   
...            ...             ...        ...  ...      ...    ...       ...   
4344             0               0          0  ...        0      0         0   
4345             0               0          0  ...        0      0         0   
4346             0               0          0  ...        0      1         1   
4347             0               0          0  ...        0      1         0   
4348             0               0          0  ...        0      0         0   

      Special Interest  Romance  Television  content_rating  runtime  \
0                    0        0           0               G      2.0   
1                    0        0           0           PG-13      2.0   
2                    0        0           0           PG-13      2.0   
3                    0        0           0               G      1.0   
4                    0        0           0               G      2.0   
...                ...      ...         ...             ...      ...   
4344                 0        0           0           PG-13      2.0   
4345                 0        0           0              PG      2.0   
4346                 0        0           0              PG      3.0   
4347                 0        0           0           PG-13      2.0   
4348                 0        0           0               R      2.0   

      production_company  audience_rating  
0     Universal Pictures               64  
1            Buena Vista               69  
2           Warner Bros.               37  
3            Buena Vista               76  
4            Buena Vista               40  
...                  ...              ...  
4344           Paramount               20  
4345              Disney               92  
4346           Paramount               91  
4347           Paramount               37  
4348              

In [13]:
df = df.dropna().reset_index()
df

index                  Unnamed: 0  Michael Lehmann  Tim Johnson  \
0         0     *batteries not included                0            0   
1         1  10 Things I Hate About You                0            0   
2         2                 10,000 B.C.                0            0   
3         3              101 Dalmatians                0            0   
4         4              101 Dalmatians                0            0   
...     ...                         ...              ...          ...   
4318   4344                 Zoolander 2                0            0   
4319   4345                    Zootopia                0            0   
4320   4346                        Zulu                0            0   
4321   4347  xXx: Return of Xander Cage                0            0   
4322   4348     xXx: State of the Union                0            0   

      Christopher Miller  Louis Leterrier  Raja Gosnell  Steve Oedekerk  \
0                      0                0             0               0   
1                      0                0             0               0   
2                      0                0             0               0   
3                      0                0             0               0   
4                      0                0             0               0   
...                  ...              ...           ...             ...   
4318                   0                0             0               0   
4319                   0                0             0               0   
4320                   0                0             0               0   
4321                   0                0             0               0   
4322                   0                0             0               0   

      Sidney Lumet  Richard Donner  ...  Western  Drama  Classics  \
0                0               0  ...        0      0         0   
1                0               0  ...        0      0         0   
2                0               0  ...        0      1         1   
3                0               0  ...        0      0         1   
4                0               0  ...        0      0         1   
...            ...             ...  ...      ...    ...       ...   
4318             0               0  ...        0      0         0   
4319             0               0  ...        0      0         0   
4320             0               0  ...        0      1         1   
4321             0               0  ...        0      1         0   
4322             0               0  ...        0      0         0   

      Special Interest  Romance  Television  content_rating  runtime  \
0                    0        0           0               G      2.0   
1                    0        0           0           PG-13      2.0   
2                    0        0           0           PG-13      2.0   
3                    0        0           0               G      1.0   
4                    0        0           0               G      2.0   
...                ...      ...         ...             ...      ...   
4318                 0        0           0           PG-13      2.0   
4319                 0        0           0              PG      2.0   
4320                 0        0           0              PG      3.0   
4321                 0        0           0           PG-13      2.0   
4322                 0        0           0               R      2.0   

      production_company  audience_rating  
0     Universal Pictures               64  
1            Buena Vista               69  
2           Warner Bros.               37  
3            Buena Vista               76  
4            Buena Vista               40  
...                  ...              ...  
4318           Paramount               20  
4319              Disney               92  
4320           Paramount               91  
4321           Paramount               37  
4322                Sony               32  

[4323

In [14]:
df = df.drop(columns=["index","Unnamed: 0"])
df

Michael Lehmann  Tim Johnson  Christopher Miller  Louis Leterrier  \
0                   0            0                   0                0   
1                   0            0                   0                0   
2                   0            0                   0                0   
3                   0            0                   0                0   
4                   0            0                   0                0   
...               ...          ...                 ...              ...   
4318                0            0                   0                0   
4319                0            0                   0                0   
4320                0            0                   0                0   
4321                0            0                   0                0   
4322                0            0                   0                0   

      Raja Gosnell  Steve Oedekerk  Sidney Lumet  Richard Donner  Joel Coen  \
0                0               0             0               0          0   
1                0               0             0               0          0   
2                0               0             0               0          0   
3                0               0             0               0          0   
4                0               0             0               0          0   
...            ...             ...           ...             ...        ...   
4318             0               0             0               0          0   
4319             0               0             0               0          0   
4320             0               0             0               0          0   
4321             0               0             0               0          0   
4322             0               0             0               0          0   

      Richard Fleischer  ...  Western  Drama  Classics  Special Interest  \
0                     0  ...        0      0         0                 0   
1                     0  ...        0      0         0                 0   
2                     0  ...        0      1         1                 0   
3                     0  ...        0      0         1                 0   
4                     0  ...        0      0         1                 0   
...                 ...  ...      ...    ...       ...               ...   
4318                  0  ...        0      0         0                 0   
4319                  0  ...        0      0         0                 0   
4320                  0  ...        0      1         1                 0   
4321                  0  ...        0      1         0                 0   
4322                  0  ...        0      0         0                 0   

      Romance  Television  content_rating  runtime  production_company  \
0           0           0               G      2.0  Universal Pictures   
1           0           0           PG-13      2.0         Buena Vista   
2           0           0           PG-13      2.0        Warner Bros.   
3           0           0               G      1.0         Buena Vista   
4           0           0               G      2.0         Buena Vista   
...       ...         ...             ...      ...                 ...   
4318        0           0           PG-13      2.0           Paramount   
4319        0           0              PG      2.0              Disney   
4320        0           0              PG      3.0           Paramount   
4321        0           0           PG-13      2.0           Paramount   
4322        0           0               R      2.0                Sony   

      audience_rating  
0                  64  
1                  69  
2                  37  
3                  76  
4                  40  
...               ...  
4318               20  
4319               92  
4320               91  
4321               37  
4322               32  

[4323 rows x 410 columns]

In [15]:
label_encoder_production = LabelEncoder()
le_pc = label_encoder_production.fit(df["production_company"])

label_encoder_rating = LabelEncoder()
le_rating = label_encoder_rating.fit(df["content_rating"])

label_encoder_runtime = LabelEncoder()
le_runtime = label_encoder_runtime.fit(df["runtime"])

In [16]:
oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(df["production_company"].values.reshape(-1,1))
pc_df = pd.DataFrame(oe_results.toarray(), columns=oe_style.categories_[0])
pc_df = pc_df.astype(int)
pc_df

20tháCenturyáFox  A24  AVCO Embassy Pictures  \
0                    0    0                      0   
1                    0    0                      0   
2                    0    0                      0   
3                    0    0                      0   
4                    0    0                      0   
...                ...  ...                    ...   
4318                 0    0                      0   
4319                 0    0                      0   
4320                 0    0                      0   
4321                 0    0                      0   
4322                 0    0                      0   

      American International Picture  Anchor Bay Entertainment  Apparition  \
0                                  0                         0           0   
1                                  0                         0           0   
2                                  0                         0           0   
3                                  0                         0           0   
4                                  0                         0           0   
...                              ...                       ...         ...   
4318                               0                         0           0   
4319                               0                         0           0   
4320                               0                         0           0   
4321                               0                         0           0   
4322                               0                         0           0   

      Artisan  Buena Vista  CBS  Columbia Pictures  ...  Touchstone Pictures  \
0           0            0    0                  0  ...                    0   
1           0            1    0                  0  ...                    0   
2           0            0    0                  0  ...                    0   
3           0            1    0                  0  ...                    0   
4           0            1    0                  0  ...                    0   
...       ...          ...  ...                ...  ...                  ...   
4318        0            0    0                  0  ...                    0   
4319        0            0    0                  0  ...                    0   
4320        0            0    0                  0  ...                    0   
4321        0            0    0                  0  ...                    0   
4322        0            0    0                  0  ...                    0   

      TriStar Pictures  Trimark Pictures  Turner Entertainment  USA Films  \
0                    0                 0                     0          0   
1                    0                 0                     0          0   
2                    0                 0                     0          0   
3                    0                 0                     0          0   
4                    0                 0                     0          0   
...                ...               ...                   ...        ...   
4318                 0                 0                     0          0   
4319                 0                 0                     0          0   
4320                 0                 0                     0          0   
4321                 0                 0                     0          0   
4322                 0                 0                     0          0   

      United Artists Pictures  Universal Pictures  Vestron Pictures  \
0                           0                   1                 0   
1                           0                   0                 0   
2                           0                   0                 0   
3                           0                   0                 0   
4                           0                   0                 0   
...                       ...                 ...               ...   
4318                        0        

In [17]:
oe_style_2 = OneHotEncoder()
oe_results_2 = oe_style.fit_transform(df["content_rating"].values.reshape(-1,1))
cr_df = pd.DataFrame(oe_results_2.toarray(), columns=oe_style.categories_[0])
cr_df = cr_df.astype(int)
cr_df

G  NC17  NR  PG  PG-13  R
0     1     0   0   0      0  0
1     0     0   0   0      1  0
2     0     0   0   0      1  0
3     1     0   0   0      0  0
4     1     0   0   0      0  0
...  ..   ...  ..  ..    ... ..
4318  0     0   0   0      1  0
4319  0     0   0   1      0  0
4320  0     0   0   1      0  0
4321  0     0   0   0      1  0
4322  0     0   0   0      0  1

[4323 rows x 6 columns]

In [18]:
oe_style_3 = OneHotEncoder()
oe_results_3 = oe_style.fit_transform(df["runtime"].values.reshape(-1,1))
rt_df = pd.DataFrame(oe_results_3.toarray(), columns=oe_style.categories_[0])
rt_df = rt_df.astype(int)
rt_df

1.0  2.0  3.0
0       0    1    0
1       0    1    0
2       0    1    0
3       1    0    0
4       0    1    0
...   ...  ...  ...
4318    0    1    0
4319    0    1    0
4320    0    0    1
4321    0    1    0
4322    0    1    0

[4323 rows x 3 columns]

In [19]:
full_df = pd.concat([df, pc_df, cr_df, rt_df], axis=1)
full_df

Michael Lehmann  Tim Johnson  Christopher Miller  Louis Leterrier  \
0                   0            0                   0                0   
1                   0            0                   0                0   
2                   0            0                   0                0   
3                   0            0                   0                0   
4                   0            0                   0                0   
...               ...          ...                 ...              ...   
4318                0            0                   0                0   
4319                0            0                   0                0   
4320                0            0                   0                0   
4321                0            0                   0                0   
4322                0            0                   0                0   

      Raja Gosnell  Steve Oedekerk  Sidney Lumet  Richard Donner  Joel Coen  \
0                0               0             0               0          0   
1                0               0             0               0          0   
2                0               0             0               0          0   
3                0               0             0               0          0   
4                0               0             0               0          0   
...            ...             ...           ...             ...        ...   
4318             0               0             0               0          0   
4319             0               0             0               0          0   
4320             0               0             0               0          0   
4321             0               0             0               0          0   
4322             0               0             0               0          0   

      Richard Fleischer  ...  Yari Film Group  G  NC17  NR  PG  PG-13  R  1.0  \
0                     0  ...                0  1     0   0   0      0  0    0   
1                     0  ...                0  0     0   0   0      1  0    0   
2                     0  ...                0  0     0   0   0      1  0    0   
3                     0  ...                0  1     0   0   0      0  0    1   
4                     0  ...                0  1     0   0   0      0  0    0   
...                 ...  ...              ... ..   ...  ..  ..    ... ..  ...   
4318                  0  ...                0  0     0   0   0      1  0    0   
4319                  0  ...                0  0     0   0   1      0  0    0   
4320                  0  ...                0  0     0   0   1      0  0    0   
4321                  0  ...                0  0     0   0   0      1  0    0   
4322                  0  ...                0  0     0   0   0      0  1    0   

      2.0  3.0  
0       1    0  
1       1    0  
2       1    0  
3       0    0  
4       1    0  
...   ...  ...  
4318    1    0  
4319    1    0  
4320    0    1  
4321    1    0  
4322    1    0  

[4323 rows x 494 columns]

In [20]:
X = full_df.drop(columns=["audience_rating","content_rating","production_company"])
y = full_df[['audience_rating']].values.reshape(-1,1)
print(X.shape, y.shape)

(4323, 491) (4323, 1)


In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

X_train.head()
dim_df=X_train.to_csv('dim_df.csv')

In [22]:
model = Sequential()
model.add(Dense(units=1500, activation='relu', input_dim=491))
model.add(Dense(units=1500, activation='relu'))
model.add(Dense(units=1500, activation='relu'))
model.add(Dense(units=1000, activation='relu'))
model.add(Dense(units=1, activation='linear'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1500)              738000    
_________________________________________________________________
dense_1 (Dense)              (None, 1500)              2251500   
_________________________________________________________________
dense_2 (Dense)              (None, 1500)              2251500   
_________________________________________________________________
dense_3 (Dense)              (None, 1000)              1501000   
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 1001      
Total params: 6,743,001
Trainable params: 6,743,001
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.compile(optimizer='adam',
              loss='mean_squared_error')

In [24]:
model.fit(
    X_train,
    y_train,
    epochs=1000,
    shuffle=True,
    verbose=2
)

Epoch 1/1000
102/102 - 3s - loss: 499.4656
Epoch 2/1000
102/102 - 3s - loss: 250.5105
Epoch 3/1000
102/102 - 3s - loss: 222.7025
Epoch 4/1000
102/102 - 3s - loss: 180.0357
Epoch 5/1000
102/102 - 4s - loss: 157.3137
Epoch 6/1000
102/102 - 4s - loss: 133.6570
Epoch 7/1000
102/102 - 4s - loss: 112.7392
Epoch 8/1000
102/102 - 4s - loss: 103.3357
Epoch 9/1000
102/102 - 4s - loss: 105.9434
Epoch 10/1000
102/102 - 4s - loss: 106.4916
Epoch 11/1000
102/102 - 4s - loss: 91.3909
Epoch 12/1000
102/102 - 4s - loss: 95.8405
Epoch 13/1000
102/102 - 4s - loss: 83.2021
Epoch 14/1000
102/102 - 4s - loss: 75.5516
Epoch 15/1000
102/102 - 4s - loss: 70.5365
Epoch 16/1000
102/102 - 4s - loss: 66.1587
Epoch 17/1000
102/102 - 4s - loss: 62.9552
Epoch 18/1000
102/102 - 4s - loss: 69.1989
Epoch 19/1000
102/102 - 4s - loss: 75.6667
Epoch 20/1000
102/102 - 4s - loss: 67.4459
Epoch 21/1000
102/102 - 4s - loss: 63.1530
Epoch 22/1000
102/102 - 4s - loss: 63.9307
Epoch 23/1000
102/102 - 4s - loss: 59.8808
Epoch 24/1

Epoch 190/1000
102/102 - 4s - loss: 30.9103
Epoch 191/1000
102/102 - 4s - loss: 30.1890
Epoch 192/1000
102/102 - 4s - loss: 30.0610
Epoch 193/1000
102/102 - 4s - loss: 29.9880
Epoch 194/1000
102/102 - 4s - loss: 31.0274
Epoch 195/1000
102/102 - 4s - loss: 31.2312
Epoch 196/1000
102/102 - 4s - loss: 32.0034
Epoch 197/1000
102/102 - 4s - loss: 30.4250
Epoch 198/1000
102/102 - 4s - loss: 31.2804
Epoch 199/1000
102/102 - 4s - loss: 30.5182
Epoch 200/1000
102/102 - 4s - loss: 31.6203
Epoch 201/1000
102/102 - 4s - loss: 30.8409
Epoch 202/1000
102/102 - 4s - loss: 30.6565
Epoch 203/1000
102/102 - 4s - loss: 30.2022
Epoch 204/1000
102/102 - 4s - loss: 29.8117
Epoch 205/1000
102/102 - 4s - loss: 31.0641
Epoch 206/1000
102/102 - 4s - loss: 30.3332
Epoch 207/1000
102/102 - 4s - loss: 30.3768
Epoch 208/1000
102/102 - 4s - loss: 31.0238
Epoch 209/1000
102/102 - 4s - loss: 31.4077
Epoch 210/1000
102/102 - 4s - loss: 30.4674
Epoch 211/1000
102/102 - 4s - loss: 30.3271
Epoch 212/1000
102/102 - 4s - lo

102/102 - 4s - loss: 28.8730
Epoch 377/1000
102/102 - 4s - loss: 29.2121
Epoch 378/1000
102/102 - 4s - loss: 28.9158
Epoch 379/1000
102/102 - 4s - loss: 29.1350
Epoch 380/1000
102/102 - 4s - loss: 28.6852
Epoch 381/1000
102/102 - 4s - loss: 28.2031
Epoch 382/1000
102/102 - 4s - loss: 28.0494
Epoch 383/1000
102/102 - 4s - loss: 27.8042
Epoch 384/1000
102/102 - 4s - loss: 27.7877
Epoch 385/1000
102/102 - 4s - loss: 29.1870
Epoch 386/1000
102/102 - 4s - loss: 29.5077
Epoch 387/1000
102/102 - 4s - loss: 28.3974
Epoch 388/1000
102/102 - 4s - loss: 28.2261
Epoch 389/1000
102/102 - 4s - loss: 28.4670
Epoch 390/1000
102/102 - 4s - loss: 28.5529
Epoch 391/1000
102/102 - 4s - loss: 28.0524
Epoch 392/1000
102/102 - 4s - loss: 28.6088
Epoch 393/1000
102/102 - 4s - loss: 28.9399
Epoch 394/1000
102/102 - 4s - loss: 28.3116
Epoch 395/1000
102/102 - 4s - loss: 27.5032
Epoch 396/1000
102/102 - 4s - loss: 27.8529
Epoch 397/1000
102/102 - 4s - loss: 27.7783
Epoch 398/1000
102/102 - 4s - loss: 27.6965
Epo

Epoch 563/1000
102/102 - 4s - loss: 27.5122
Epoch 564/1000
102/102 - 4s - loss: 27.3735
Epoch 565/1000
102/102 - 4s - loss: 27.3684
Epoch 566/1000
102/102 - 4s - loss: 27.9458
Epoch 567/1000
102/102 - 4s - loss: 27.4360
Epoch 568/1000
102/102 - 4s - loss: 27.5077
Epoch 569/1000
102/102 - 4s - loss: 28.1723
Epoch 570/1000
102/102 - 4s - loss: 27.9306
Epoch 571/1000
102/102 - 4s - loss: 27.8056
Epoch 572/1000
102/102 - 4s - loss: 27.4078
Epoch 573/1000
102/102 - 4s - loss: 27.0660
Epoch 574/1000
102/102 - 4s - loss: 27.1812
Epoch 575/1000
102/102 - 4s - loss: 27.2362
Epoch 576/1000
102/102 - 4s - loss: 27.4383
Epoch 577/1000
102/102 - 4s - loss: 27.7059
Epoch 578/1000
102/102 - 4s - loss: 27.6212
Epoch 579/1000
102/102 - 4s - loss: 27.2205
Epoch 580/1000
102/102 - 4s - loss: 27.5238
Epoch 581/1000
102/102 - 4s - loss: 27.2136
Epoch 582/1000
102/102 - 4s - loss: 27.8548
Epoch 583/1000
102/102 - 4s - loss: 27.5678
Epoch 584/1000
102/102 - 4s - loss: 27.0631
Epoch 585/1000
102/102 - 4s - lo

102/102 - 4s - loss: 27.0059
Epoch 750/1000
102/102 - 4s - loss: 27.0622
Epoch 751/1000
102/102 - 4s - loss: 26.8343
Epoch 752/1000
102/102 - 4s - loss: 26.6192
Epoch 753/1000
102/102 - 4s - loss: 28.0955
Epoch 754/1000
102/102 - 4s - loss: 27.0893
Epoch 755/1000
102/102 - 4s - loss: 26.6727
Epoch 756/1000
102/102 - 4s - loss: 26.9013
Epoch 757/1000
102/102 - 4s - loss: 26.8873
Epoch 758/1000
102/102 - 4s - loss: 26.8930
Epoch 759/1000
102/102 - 4s - loss: 27.0122
Epoch 760/1000
102/102 - 4s - loss: 27.2902
Epoch 761/1000
102/102 - 4s - loss: 27.1792
Epoch 762/1000
102/102 - 4s - loss: 26.9320
Epoch 763/1000
102/102 - 4s - loss: 26.6378
Epoch 764/1000
102/102 - 4s - loss: 27.3508
Epoch 765/1000
102/102 - 4s - loss: 26.9948
Epoch 766/1000
102/102 - 4s - loss: 26.9574
Epoch 767/1000
102/102 - 4s - loss: 26.9588
Epoch 768/1000
102/102 - 4s - loss: 26.8784
Epoch 769/1000
102/102 - 4s - loss: 27.0778
Epoch 770/1000
102/102 - 4s - loss: 27.0706
Epoch 771/1000
102/102 - 4s - loss: 27.4484
Epo

Epoch 936/1000
102/102 - 4s - loss: 27.0933
Epoch 937/1000
102/102 - 4s - loss: 26.8462
Epoch 938/1000
102/102 - 4s - loss: 26.5319
Epoch 939/1000
102/102 - 4s - loss: 26.8329
Epoch 940/1000
102/102 - 4s - loss: 26.5464
Epoch 941/1000
102/102 - 4s - loss: 26.6120
Epoch 942/1000
102/102 - 4s - loss: 26.5764
Epoch 943/1000
102/102 - 4s - loss: 26.6331
Epoch 944/1000
102/102 - 4s - loss: 26.4242
Epoch 945/1000
102/102 - 4s - loss: 26.2861
Epoch 946/1000
102/102 - 4s - loss: 26.4254
Epoch 947/1000
102/102 - 4s - loss: 26.7503
Epoch 948/1000
102/102 - 4s - loss: 26.6691
Epoch 949/1000
102/102 - 4s - loss: 26.4944
Epoch 950/1000
102/102 - 4s - loss: 26.3248
Epoch 951/1000
102/102 - 4s - loss: 26.7819
Epoch 952/1000
102/102 - 4s - loss: 26.4864
Epoch 953/1000
102/102 - 4s - loss: 26.7894
Epoch 954/1000
102/102 - 4s - loss: 26.6670
Epoch 955/1000
102/102 - 4s - loss: 26.7011
Epoch 956/1000
102/102 - 4s - loss: 26.6763
Epoch 957/1000
102/102 - 4s - loss: 26.3083
Epoch 958/1000
102/102 - 4s - lo

In [32]:
model.predict(X_test.iloc[1].values.reshape(1,-1))

array([[46.63656]], dtype=float32)

In [33]:
y_test[1]

array([49], dtype=int64)

In [62]:
# model.save("model.h5")

In [63]:
# import pickle

# dump(model, open('model.pkl', 'wb'))

TypeError: cannot pickle 'weakref' object

In [64]:
from pickle import dump

In [65]:
# filename='model.sav'

# pickle.dump(model, open(filename, 'wb'))

TypeError: cannot pickle 'weakref' object

In [54]:
error=[]
for i in range(0,len(X_test)):
    error.append(abs(model.predict(X_test.iloc[i].values.reshape(1,-1))-y_test[1]))

In [55]:
error

[array([[36.39044952]]),
 array([[2.36344147]]),
 array([[12.77386475]]),
 array([[9.54053116]]),
 array([[4.6975174]]),
 array([[14.64880371]]),
 array([[1.00233078]]),
 array([[27.6558609]]),
 array([[19.12496185]]),
 array([[17.70090485]]),
 array([[15.37042999]]),
 array([[11.66023254]]),
 array([[3.76944351]]),
 array([[31.7201004]]),
 array([[5.21335602]]),
 array([[3.51438141]]),
 array([[9.69454575]]),
 array([[9.3030777]]),
 array([[19.86779022]]),
 array([[12.96564865]]),
 array([[8.73340225]]),
 array([[2.09615707]]),
 array([[14.20859146]]),
 array([[38.65670776]]),
 array([[0.81929016]]),
 array([[14.00299454]]),
 array([[3.40291214]]),
 array([[20.97805023]]),
 array([[23.17642212]]),
 array([[3.62971497]]),
 array([[15.32653809]]),
 array([[4.82888031]]),
 array([[4.06899643]]),
 array([[23.57131958]]),
 array([[4.69144821]]),
 array([[43.85119629]]),
 array([[25.09468842]]),
 array([[36.50016785]]),
 array([[31.5391922]]),
 array([[40.33518982]]),
 array([[16.40242004]]

In [57]:
sum(error)/len(error)

array([[17.08419259]])

In [58]:
error.sort()

In [61]:
n=len(error)
if n % 2 == 0:
    median1 = error[n//2]
    median2 = error[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = error[n//2]
print("Median is: " + str(median))

Median is: [[14.99316406]]
